CFLAGS = -Wall -Wextra -g
all: run_server run_client
run_server:
	gcc $(CFLAGS) -o server212 server212.c -lm

run_client:
	gcc $(CFLAGS) -o client client.c

clean:
	rm server212.o client.o server212 client



